import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + "bg-white text-black dark:bg-black dark:text-white "}>
        <Navbar />
        <main className="flex max-w-screen-xl min-h-screen flex-col items-center justify-between pt-24 px-4 mx-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
